### ISSUE TITLE
Reporting a string of error when running.

### ISSUE THREAD

**Issue by scillidan** [jmarxuach/BatchPDFSign#19]
I remember when I use it at the beginning of the year, it run successfully.
today, I tried to use it but it said:
```cmd
D:\home λ gsudo java -jar ..\batchpdfsign-portable.jar -k `pfx` -p `password` -i `pdf` -o `_out.pdf`        
Exception in thread "main" com.itextpdf.kernel.PdfException: Unknown PdfException.
        at com.itextpdf.signatures.PdfPKCS7.getEncodedPKCS7(PdfPKCS7.java:934)
        at com.itextpdf.signatures.PdfSigner.signDetached(PdfSigner.java:648)
        at com.itextpdf.signatures.PdfSigner.signDetached(PdfSigner.java:538)
        at BatchPDFSign.lib.BatchPDFSign.signFile(BatchPDFSign.java:77)
        at BatchPDFSign.portable.Main.main(Main.java:48)
Caused by: java.net.SocketException: Permission denied: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
        at com.itextpdf.signatures.SignUtils.getTsaResponseForUserRequest(SignUtils.java:280)
        at com.itextpdf.signatures.TSAClientBouncyCastle.getTSAResponse(TSAClientBouncyCastle.java:268)
        at com.itextpdf.signatures.TSAClientBouncyCastle.getTimeStampToken(TSAClientBouncyCastle.java:227)
        at com.itextpdf.signatures.PdfPKCS7.getEncodedPKCS7(PdfPKCS7.java:900)
        ... 4 more
```

**Comment by jmarxuach** [comment]
In your command line there is no key file path ? 

` -k `pfx`

is not a file.

**Comment by jmarxuach** [comment]
Signing need add document the timestamp, using itext, we have com.itextpdf.text.pdf.security.TSAClient abstract interface. I Thing this needs to be online.

**Comment by scillidan** [comment]
Seems the error appears to have been caused by a temporary network problem then.
It can run now.
Thanks :)
