### ISSUE TITLE
com.itextpdf.kernel.PdfException: Append mode requires a document without errors, even if recovery is possible

### ISSUE THREAD

**Issue by jmarxuach** [jmarxuach/BatchPDFSign#6]
Searching in google I found [this](https://stackoverflow.com/questions/47281240/append-mode-requires-a-document-without-errors-even-if-recovery-is-possible) that suggest there is a bug in itext7, but im not sure.

I have a PDF that throws this error, but i can't attach because is confidential.

**Comment by jmarxuach** [comment]
That's the exception 

[main] ERROR com.itextpdf.kernel.pdf.PdfReader - Error occurred while reading cross reference table. Cross reference table will be rebuilt.
com.itextpdf.io.IOException: Error at file pointer 46,820.
        at com.itextpdf.io.source.PdfTokenizer.throwError(PdfTokenizer.java:686)
        at com.itextpdf.kernel.pdf.PdfReader.readXrefSection(PdfReader.java:1011)
        at com.itextpdf.kernel.pdf.PdfReader.readXref(PdfReader.java:929)
        at com.itextpdf.kernel.pdf.PdfReader.readPdf(PdfReader.java:677)
        at com.itextpdf.kernel.pdf.PdfDocument.open(PdfDocument.java:1871)
        at com.itextpdf.kernel.pdf.PdfDocument.<init>(PdfDocument.java:324)
        at com.itextpdf.signatures.PdfSigner.initDocument(PdfSigner.java:306)
        at com.itextpdf.signatures.PdfSigner.<init>(PdfSigner.java:288)
        at com.itextpdf.signatures.PdfSigner.<init>(PdfSigner.java:271)
        at BatchPDFSign.lib.BatchPDFSign.signFile(BatchPDFSign.java:73)
        at BatchPDFSign.portable.Main.main(Main.java:48)
Caused by: com.itextpdf.io.IOException: file position {0} cross reference entry in this xref subsection.
        ... 11 more
Exception in thread "main" com.itextpdf.kernel.PdfException: Append mode requires a document without errors, even if recovery is possible.
        at com.itextpdf.kernel.pdf.PdfDocument.open(PdfDocument.java:1918)
        at com.itextpdf.kernel.pdf.PdfDocument.<init>(PdfDocument.java:324)
        at com.itextpdf.signatures.PdfSigner.initDocument(PdfSigner.java:306)
        at com.itextpdf.signatures.PdfSigner.<init>(PdfSigner.java:288)
        at com.itextpdf.signatures.PdfSigner.<init>(PdfSigner.java:271)
        at BatchPDFSign.lib.BatchPDFSign.signFile(BatchPDFSign.java:73)
        at BatchPDFSign.portable.Main.main(Main.java:48)

**Comment by Jocomol** [comment]
I've tried it with the sample file supplied by the OP of the question, found [here](https://www.dropbox.com/s/i7eeamw9xouf76l/word.pdf?dl=0). Can you the file or some similar file?

The version of iText7 the OP used was 7.0.4, we use 7.1.11. So I think the bug would be fixed already.

**Comment by jmarxuach** [comment]
> I've tried it with the sample file supplied by the OP of the question, found [here](https://www.dropbox.com/s/i7eeamw9xouf76l/word.pdf?dl=0). Can you the file or some similar file?
> 
> The version of iText7 the OP used was 7.0.4, we use 7.1.11. So I think the bug would be fixed already.

I agree. Look, if I try to with following code

`StampingProperties properties = new StampingProperties();`

instead of 

`StampingProperties properties = new StampingProperties().preserveEncryption().useAppendMode();`

It works ! 

I think **useAppendModemode** and **preserveEncryption**  requires a document without errors, even if recovery is possible in itext7.

**Comment by Jocomol** [comment]
https://github.com/jmarxuach/BatchPDFSign/pull/7

**Comment by Jocomol** [comment]
I'll have to test if removing preserveEncyription() still works with PDF/A

**Comment by Jocomol** [comment]
@jmarxuach can you try out if version 1.0.5.1 works, because I only removed .useAppendMode().

**Comment by jmarxuach** [comment]
> @jmarxuach can you try out if version 1.0.5.1 works, because I only removed .useAppendMode().

It Works !! Even if prints the exception

```
[main] ERROR com.itextpdf.kernel.pdf.PdfReader - Error occurred while reading cross reference table. Cross reference table will be rebuilt.
com.itextpdf.io.IOException: Error at file pointer 46,820.
        at com.itextpdf.io.source.PdfTokenizer.throwError(PdfTokenizer.java:686)
        at com.itextpdf.kernel.pdf.PdfReader.readXrefSection(PdfReader.java:1011)
        at com.itextpdf.kernel.pdf.PdfReader.readXref(PdfReader.java:929)
        at com.itextpdf.kernel.pdf.PdfReader.readPdf(PdfReader.java:677)
        at com.itextpdf.kernel.pdf.PdfDocument.open(PdfDocument.java:1871)
        at com.itextpdf.kernel.pdf.PdfDocument.<init>(PdfDocument.java:324)
        at com.itextpdf.signatures.PdfSigner.initDocument(PdfSigner.java:306)
        at com.itextpdf.signatures.PdfSigner.<init>(PdfSigner.java:288)
        at com.itextpdf.signatures.PdfSigner.<init>(PdfSigner.java:271)
        at BatchPDFSign.lib.BatchPDFSign.signFile(BatchPDFSign.java:75)
        at BatchPDFSign.portable.Main.main(Main.java:48)
Caused by: com.itextpdf.io.IOException: file position {0} cross reference entry in this xref subsection.
        ... 11 more
[main] ERROR com.itextpdf.kernel.pdf.PdfReader - Error occurred while reading cross reference table. Cross reference table will be rebuilt.
com.itextpdf.io.IOException: Error at file pointer 46,820.
        at com.itextpdf.io.source.PdfTokenizer.throwError(PdfTokenizer.java:686)
        at com.itextpdf.kernel.pdf.PdfReader.readXrefSection(PdfReader.java:1011)
        at com.itextpdf.kernel.pdf.PdfReader.readXref(PdfReader.java:929)
        at com.itextpdf.kernel.pdf.PdfReader.readPdf(PdfReader.java:677)
        at com.itextpdf.kernel.pdf.PdfDocument.open(PdfDocument.java:1871)
        at com.itextpdf.kernel.pdf.PdfDocument.<init>(PdfDocument.java:324)
        at com.itextpdf.signatures.PdfSigner.initDocument(PdfSigner.java:306)
        at com.itextpdf.signatures.PdfSigner.<init>(PdfSigner.java:288)
        at com.itextpdf.signatures.PdfSigner.<init>(PdfSigner.java:271)
        at BatchPDFSign.lib.BatchPDFSign.signFile(BatchPDFSign.java:79)
        at BatchPDFSign.portable.Main.main(Main.java:48)
Caused by: com.itextpdf.io.IOException: file position {0} cross reference entry in this xref subsection.
        ... 11 more
[main] INFO com.itextpdf.signatures.TSAClientBouncyCastle - Timestamp generated: Thu Jul 23 14:54:01 CEST 2020
```

**Comment by Jocomol** [comment]
@jmarxuach your pdf file is probably damaged, can you try with a similar file?

**Comment by jmarxuach** [comment]
> @jmarxuach your pdf file is probably damaged, can you try with a similar file?

My Pdf file is 1,4 version and is created with https://wkhtmltopdf.org/  I can open it with acrobat reader DC and the signed PDF too. 

Anyway, now BatchPDFSign works even if prints the exception. My PDF file is a worst case test.  I have created a release [v1.0.5.1](https://github.com/jmarxuach/BatchPDFSign/releases/tag/v1.0.5.1)

To me, issue is solved. May be I will open a new one to remember to solve the exception print.
